package errs

import "syscall"

// errnoNames maps each darwin errno to its symbolic name. The syscall constants
// carry this platform's numbers.
//
// Aliases get one fixed name on both platforms: EAGAIN (not EWOULDBLOCK),
// ENOTSUP (not EOPNOTSUPP). EOPNOTSUPP has its own number here, which also
// maps to ENOTSUP. ELAST marks the end of the range and is not an error.
var errnoNames = map[syscall.Errno]string{
	syscall.EPERM:           "EPERM",
	syscall.ENOENT:          "ENOENT",
	syscall.ESRCH:           "ESRCH",
	syscall.EINTR:           "EINTR",
	syscall.EIO:             "EIO",
	syscall.ENXIO:           "ENXIO",
	syscall.E2BIG:           "E2BIG",
	syscall.ENOEXEC:         "ENOEXEC",
	syscall.EBADF:           "EBADF",
	syscall.ECHILD:          "ECHILD",
	syscall.EDEADLK:         "EDEADLK",
	syscall.ENOMEM:          "ENOMEM",
	syscall.EACCES:          "EACCES",
	syscall.EFAULT:          "EFAULT",
	syscall.ENOTBLK:         "ENOTBLK",
	syscall.EBUSY:           "EBUSY",
	syscall.EEXIST:          "EEXIST",
	syscall.EXDEV:           "EXDEV",
	syscall.ENODEV:          "ENODEV",
	syscall.ENOTDIR:         "ENOTDIR",
	syscall.EISDIR:          "EISDIR",
	syscall.EINVAL:          "EINVAL",
	syscall.ENFILE:          "ENFILE",
	syscall.EMFILE:          "EMFILE",
	syscall.ENOTTY:          "ENOTTY",
	syscall.ETXTBSY:         "ETXTBSY",
	syscall.EFBIG:           "EFBIG",
	syscall.ENOSPC:          "ENOSPC",
	syscall.ESPIPE:          "ESPIPE",
	syscall.EROFS:           "EROFS",
	syscall.EMLINK:          "EMLINK",
	syscall.EPIPE:           "EPIPE",
	syscall.EDOM:            "EDOM",
	syscall.ERANGE:          "ERANGE",
	syscall.EAGAIN:          "EAGAIN",
	syscall.EINPROGRESS:     "EINPROGRESS",
	syscall.EALREADY:        "EALREADY",
	syscall.ENOTSOCK:        "ENOTSOCK",
	syscall.EDESTADDRREQ:    "EDESTADDRREQ",
	syscall.EMSGSIZE:        "EMSGSIZE",
	syscall.EPROTOTYPE:      "EPROTOTYPE",
	syscall.ENOPROTOOPT:     "ENOPROTOOPT",
	syscall.EPROTONOSUPPORT: "EPROTONOSUPPORT",
	syscall.ESOCKTNOSUPPORT: "ESOCKTNOSUPPORT",
	syscall.ENOTSUP:         "ENOTSUP",
	syscall.EPFNOSUPPORT:    "EPFNOSUPPORT",
	syscall.EAFNOSUPPORT:    "EAFNOSUPPORT",
	syscall.EADDRINUSE:      "EADDRINUSE",
	syscall.EADDRNOTAVAIL:   "EADDRNOTAVAIL",
	syscall.ENETDOWN:        "ENETDOWN",
	syscall.ENETUNREACH:     "ENETUNREACH",
	syscall.ENETRESET:       "ENETRESET",
	syscall.ECONNABORTED:    "ECONNABORTED",
	syscall.ECONNRESET:      "ECONNRESET",
	syscall.ENOBUFS:         "ENOBUFS",
	syscall.EISCONN:         "EISCONN",
	syscall.ENOTCONN:        "ENOTCONN",
	syscall.ESHUTDOWN:       "ESHUTDOWN",
	syscall.ETOOMANYREFS:    "ETOOMANYREFS",
	syscall.ETIMEDOUT:       "ETIMEDOUT",
	syscall.ECONNREFUSED:    "ECONNREFUSED",
	syscall.ELOOP:           "ELOOP",
	syscall.ENAMETOOLONG:    "ENAMETOOLONG",
	syscall.EHOSTDOWN:       "EHOSTDOWN",
	syscall.EHOSTUNREACH:    "EHOSTUNREACH",
	syscall.ENOTEMPTY:       "ENOTEMPTY",
	syscall.EPROCLIM:        "EPROCLIM",
	syscall.EUSERS:          "EUSERS",
	syscall.EDQUOT:          "EDQUOT",
	syscall.ESTALE:          "ESTALE",
	syscall.EREMOTE:         "EREMOTE",
	syscall.EBADRPC:         "EBADRPC",
	syscall.ERPCMISMATCH:    "ERPCMISMATCH",
	syscall.EPROGUNAVAIL:    "EPROGUNAVAIL",
	syscall.EPROGMISMATCH:   "EPROGMISMATCH",
	syscall.EPROCUNAVAIL:    "EPROCUNAVAIL",
	syscall.ENOLCK:          "ENOLCK",
	syscall.ENOSYS:          "ENOSYS",
	syscall.EFTYPE:          "EFTYPE",
	syscall.EAUTH:           "EAUTH",
	syscall.ENEEDAUTH:       "ENEEDAUTH",
	syscall.EPWROFF:         "EPWROFF",
	syscall.EDEVERR:         "EDEVERR",
	syscall.EOVERFLOW:       "EOVERFLOW",
	syscall.EBADEXEC:        "EBADEXEC",
	syscall.EBADARCH:        "EBADARCH",
	syscall.ESHLIBVERS:      "ESHLIBVERS",
	syscall.EBADMACHO:       "EBADMACHO",
	syscall.ECANCELED:       "ECANCELED",
	syscall.EIDRM:           "EIDRM",
	syscall.ENOMSG:          "ENOMSG",
	syscall.EILSEQ:          "EILSEQ",
	syscall.ENOATTR:         "ENOATTR",
	syscall.EBADMSG:         "EBADMSG",
	syscall.EMULTIHOP:       "EMULTIHOP",
	syscall.ENODATA:         "ENODATA",
	syscall.ENOLINK:         "ENOLINK",
	syscall.ENOSR:           "ENOSR",
	syscall.ENOSTR:          "ENOSTR",
	syscall.EPROTO:          "EPROTO",
	syscall.ETIME:           "ETIME",
	syscall.EOPNOTSUPP:      "ENOTSUP",
	syscall.ENOPOLICY:       "ENOPOLICY",
	syscall.ENOTRECOVERABLE: "ENOTRECOVERABLE",
	syscall.EOWNERDEAD:      "EOWNERDEAD",
	syscall.Errno(106):      "EQFULL", // not defined by syscall on every darwin architecture
}
