//go:build linux && (amd64 || arm64)

package errs

import "syscall"

// errnoNames maps each linux errno to its symbolic name. The syscall constants
// carry this platform's numbers. Only the supported architectures build it
// (design-spec.md, Supported platforms): numbers differ elsewhere (on mips,
// 133 is EISCONN and EDEADLOCK has its own number), so a build on another
// linux architecture fails for want of errnoNames rather than misnaming.
//
// Aliases sharing a number get one fixed name on both platforms: EAGAIN
// (not EWOULDBLOCK), ENOTSUP (not EOPNOTSUPP), EDEADLK (not EDEADLOCK).
var errnoNames = map[syscall.Errno]string{
	syscall.EPERM:           "EPERM",
	syscall.ENOENT:          "ENOENT",
	syscall.ESRCH:           "ESRCH",
	syscall.EINTR:           "EINTR",
	syscall.EIO:             "EIO",
	syscall.ENXIO:           "ENXIO",
	syscall.E2BIG:           "E2BIG",
	syscall.ENOEXEC:         "ENOEXEC",
	syscall.EBADF:           "EBADF",
	syscall.ECHILD:          "ECHILD",
	syscall.EAGAIN:          "EAGAIN",
	syscall.ENOMEM:          "ENOMEM",
	syscall.EACCES:          "EACCES",
	syscall.EFAULT:          "EFAULT",
	syscall.ENOTBLK:         "ENOTBLK",
	syscall.EBUSY:           "EBUSY",
	syscall.EEXIST:          "EEXIST",
	syscall.EXDEV:           "EXDEV",
	syscall.ENODEV:          "ENODEV",
	syscall.ENOTDIR:         "ENOTDIR",
	syscall.EISDIR:          "EISDIR",
	syscall.EINVAL:          "EINVAL",
	syscall.ENFILE:          "ENFILE",
	syscall.EMFILE:          "EMFILE",
	syscall.ENOTTY:          "ENOTTY",
	syscall.ETXTBSY:         "ETXTBSY",
	syscall.EFBIG:           "EFBIG",
	syscall.ENOSPC:          "ENOSPC",
	syscall.ESPIPE:          "ESPIPE",
	syscall.EROFS:           "EROFS",
	syscall.EMLINK:          "EMLINK",
	syscall.EPIPE:           "EPIPE",
	syscall.EDOM:            "EDOM",
	syscall.ERANGE:          "ERANGE",
	syscall.EDEADLK:         "EDEADLK",
	syscall.ENAMETOOLONG:    "ENAMETOOLONG",
	syscall.ENOLCK:          "ENOLCK",
	syscall.ENOSYS:          "ENOSYS",
	syscall.ENOTEMPTY:       "ENOTEMPTY",
	syscall.ELOOP:           "ELOOP",
	syscall.ENOMSG:          "ENOMSG",
	syscall.EIDRM:           "EIDRM",
	syscall.ECHRNG:          "ECHRNG",
	syscall.EL2NSYNC:        "EL2NSYNC",
	syscall.EL3HLT:          "EL3HLT",
	syscall.EL3RST:          "EL3RST",
	syscall.ELNRNG:          "ELNRNG",
	syscall.EUNATCH:         "EUNATCH",
	syscall.ENOCSI:          "ENOCSI",
	syscall.EL2HLT:          "EL2HLT",
	syscall.EBADE:           "EBADE",
	syscall.EBADR:           "EBADR",
	syscall.EXFULL:          "EXFULL",
	syscall.ENOANO:          "ENOANO",
	syscall.EBADRQC:         "EBADRQC",
	syscall.EBADSLT:         "EBADSLT",
	syscall.EBFONT:          "EBFONT",
	syscall.ENOSTR:          "ENOSTR",
	syscall.ENODATA:         "ENODATA",
	syscall.ETIME:           "ETIME",
	syscall.ENOSR:           "ENOSR",
	syscall.ENONET:          "ENONET",
	syscall.ENOPKG:          "ENOPKG",
	syscall.EREMOTE:         "EREMOTE",
	syscall.ENOLINK:         "ENOLINK",
	syscall.EADV:            "EADV",
	syscall.ESRMNT:          "ESRMNT",
	syscall.ECOMM:           "ECOMM",
	syscall.EPROTO:          "EPROTO",
	syscall.EMULTIHOP:       "EMULTIHOP",
	syscall.EDOTDOT:         "EDOTDOT",
	syscall.EBADMSG:         "EBADMSG",
	syscall.EOVERFLOW:       "EOVERFLOW",
	syscall.ENOTUNIQ:        "ENOTUNIQ",
	syscall.EBADFD:          "EBADFD",
	syscall.EREMCHG:         "EREMCHG",
	syscall.ELIBACC:         "ELIBACC",
	syscall.ELIBBAD:         "ELIBBAD",
	syscall.ELIBSCN:         "ELIBSCN",
	syscall.ELIBMAX:         "ELIBMAX",
	syscall.ELIBEXEC:        "ELIBEXEC",
	syscall.EILSEQ:          "EILSEQ",
	syscall.ERESTART:        "ERESTART",
	syscall.ESTRPIPE:        "ESTRPIPE",
	syscall.EUSERS:          "EUSERS",
	syscall.ENOTSOCK:        "ENOTSOCK",
	syscall.EDESTADDRREQ:    "EDESTADDRREQ",
	syscall.EMSGSIZE:        "EMSGSIZE",
	syscall.EPROTOTYPE:      "EPROTOTYPE",
	syscall.ENOPROTOOPT:     "ENOPROTOOPT",
	syscall.EPROTONOSUPPORT: "EPROTONOSUPPORT",
	syscall.ESOCKTNOSUPPORT: "ESOCKTNOSUPPORT",
	syscall.ENOTSUP:         "ENOTSUP",
	syscall.EPFNOSUPPORT:    "EPFNOSUPPORT",
	syscall.EAFNOSUPPORT:    "EAFNOSUPPORT",
	syscall.EADDRINUSE:      "EADDRINUSE",
	syscall.EADDRNOTAVAIL:   "EADDRNOTAVAIL",
	syscall.ENETDOWN:        "ENETDOWN",
	syscall.ENETUNREACH:     "ENETUNREACH",
	syscall.ENETRESET:       "ENETRESET",
	syscall.ECONNABORTED:    "ECONNABORTED",
	syscall.ECONNRESET:      "ECONNRESET",
	syscall.ENOBUFS:         "ENOBUFS",
	syscall.EISCONN:         "EISCONN",
	syscall.ENOTCONN:        "ENOTCONN",
	syscall.ESHUTDOWN:       "ESHUTDOWN",
	syscall.ETOOMANYREFS:    "ETOOMANYREFS",
	syscall.ETIMEDOUT:       "ETIMEDOUT",
	syscall.ECONNREFUSED:    "ECONNREFUSED",
	syscall.EHOSTDOWN:       "EHOSTDOWN",
	syscall.EHOSTUNREACH:    "EHOSTUNREACH",
	syscall.EALREADY:        "EALREADY",
	syscall.EINPROGRESS:     "EINPROGRESS",
	syscall.ESTALE:          "ESTALE",
	syscall.EUCLEAN:         "EUCLEAN",
	syscall.ENOTNAM:         "ENOTNAM",
	syscall.ENAVAIL:         "ENAVAIL",
	syscall.EISNAM:          "EISNAM",
	syscall.EREMOTEIO:       "EREMOTEIO",
	syscall.EDQUOT:          "EDQUOT",
	syscall.ENOMEDIUM:       "ENOMEDIUM",
	syscall.EMEDIUMTYPE:     "EMEDIUMTYPE",
	syscall.ECANCELED:       "ECANCELED",
	syscall.ENOKEY:          "ENOKEY",
	syscall.EKEYEXPIRED:     "EKEYEXPIRED",
	syscall.EKEYREVOKED:     "EKEYREVOKED",
	syscall.EKEYREJECTED:    "EKEYREJECTED",
	syscall.EOWNERDEAD:      "EOWNERDEAD",
	syscall.ENOTRECOVERABLE: "ENOTRECOVERABLE",
	syscall.ERFKILL:         "ERFKILL",
	syscall.Errno(133):      "EHWPOISON", // not defined by syscall on every linux architecture
}
